package io.github.silentdevelopment.headdb.paper.message;

import org.jetbrains.annotations.NotNull;

public enum MessageKey {

    // Command

    COMMAND_ERROR_NO_PERMISSION("command.error.no-permission"),
    COMMAND_ERROR_UNKNOWN_COMMAND("command.error.unknown-command"),
    COMMAND_ERROR_NO_HANDLER("command.error.no-handler"),
    COMMAND_ERROR_INVALID_USAGE("command.error.invalid-usage"),
    COMMAND_ERROR_VALID_USAGES("command.error.valid-usages"),

    COMMAND_USAGE_SEARCH("command.usage.search"),
    COMMAND_USAGE_GIVE("command.usage.give"),
    COMMAND_USAGE_CONSOLE_GIVE("command.usage.console-give"),
    COMMAND_USAGE_INFO_CONSOLE("command.usage.info-console"),
    COMMAND_USAGE_OPEN_CONSOLE_SELF("command.usage.open-console-self"),
    COMMAND_USAGE_OPEN_CONSOLE_TARGET("command.usage.open-console-target"),
    COMMAND_USAGE_RANDOM_CONSOLE("command.usage.random-console"),
    COMMAND_USAGE_ITEMCACHE("command.usage.itemcache"),
    COMMAND_USAGE_PLAYER("command.usage.player"),
    COMMAND_USAGE_PLAYER_ARGS("command.usage.player-args"),
    COMMAND_USAGE_CUSTOM("command.usage.custom"),
    COMMAND_USAGE_CUSTOM_CREATE("command.usage.custom-create"),
    COMMAND_USAGE_CUSTOM_RENAME("command.usage.custom-rename"),
    COMMAND_USAGE_CUSTOM_GIVE("command.usage.custom-give"),
    COMMAND_USAGE_CUSTOM_GIVE_CONSOLE("command.usage.custom-give-console"),
    COMMAND_USAGE_EDIT("command.usage.edit"),
    COMMAND_USAGE_EDIT_NAME("command.usage.edit-name"),
    COMMAND_USAGE_EDIT_LORE_SET("command.usage.edit-lore-set"),
    COMMAND_USAGE_EDIT_TAG_ADD("command.usage.edit-tag-add"),
    COMMAND_USAGE_EDIT_TAG_REMOVE("command.usage.edit-tag-remove"),
    COMMAND_USAGE_EDIT_TAGS_REPLACE("command.usage.edit-tags-replace"),
    COMMAND_USAGE_EDIT_CATEGORY("command.usage.edit-category"),
    COMMAND_USAGE_GIVE_FULL("command.usage.give-full"),
    COMMAND_USAGE_TAGS_CREATE("command.usage.tags-create"),
    COMMAND_USAGE_TAGS_DELETE("command.usage.tags-delete"),
    COMMAND_USAGE_COLLECTIONS_CREATE("command.usage.collections-create"),
    COMMAND_USAGE_COLLECTIONS_DELETE("command.usage.collections-delete"),

    COMMAND_ERROR_INVALID_ARGUMENT("command.error.invalid-argument"),
    COMMAND_ERROR_UNKNOWN_HEAD("command.error.unknown-head"),
    COMMAND_ERROR_PLAYER_NOT_ONLINE("command.error.player-not-online"),
    COMMAND_ERROR_TARGET_EMPTY("command.error.target-empty"),
    COMMAND_ERROR_NO_GIVE_OTHERS("command.error.no-give-others"),
    COMMAND_ERROR_INVENTORY_FULL("command.error.inventory-full"),
    COMMAND_ERROR_UNKNOWN_CATEGORY("command.error.unknown-category"),
    COMMAND_ERROR_HELD_HEAD_REQUIRED("command.error.held-head-required"),
    COMMAND_ERROR_RANDOM_EMPTY("command.error.random-empty"),
    COMMAND_ERROR_PAGE_MIN("command.error.page-min"),
    COMMAND_ERROR_PAGE_MAX("command.error.page-max"),
    COMMAND_ERROR_LIMIT_MIN("command.error.limit-min"),
    COMMAND_ERROR_LIMIT_MAX("command.error.limit-max"),
    COMMAND_ERROR_AMOUNT_NUMBER("command.error.amount-number"),
    COMMAND_ERROR_AMOUNT_RANGE("command.error.amount-range"),
    COMMAND_ERROR_RANDOM_AMOUNT_RANGE("command.error.random-amount-range"),
    COMMAND_ERROR_RANDOM_ARGUMENT("command.error.random-argument"),
    COMMAND_ERROR_CONSOLE_CREATEHELD("command.error.console-createheld"),
    COMMAND_ERROR_AMBIGUOUS_GIVE("command.error.ambiguous-give"),
    COMMAND_ERROR_AMBIGUOUS_GIVE_AMOUNT("command.error.ambiguous-give-amount"),
    COMMAND_ERROR_SEARCH_EMPTY("command.error.search-empty"),
    COMMAND_ERROR_SEARCH_SINGLE_ID("command.error.search-single-id"),
    COMMAND_ERROR_SEARCH_EMPTY_ID("command.error.search-empty-id"),
    COMMAND_ERROR_SEARCH_IDS_EMPTY_ID("command.error.search-ids-empty-id"),
    COMMAND_ERROR_HEAD_ID_EMPTY("command.error.head-id-empty"),
    COMMAND_ERROR_HEAD_ID_PREFIX("command.error.head-id-prefix"),
    COMMAND_ERROR_REMOTE_ID_EMPTY("command.error.remote-id-empty"),
    COMMAND_ERROR_REMOTE_ID_NUMERIC("command.error.remote-id-numeric"),
    COMMAND_ERROR_REMOTE_ID_LARGE("command.error.remote-id-large"),
    COMMAND_ERROR_CUSTOM_ID_EMPTY("command.error.custom-id-empty"),
    COMMAND_ERROR_CUSTOM_ID_REQUIRED("command.error.custom-id-required"),
    COMMAND_ERROR_UNKNOWN_CUSTOM_HEAD("command.error.unknown-custom-head"),
    COMMAND_ERROR_PLAYER_ID_EMPTY("command.error.player-id-empty"),
    COMMAND_ERROR_PLAYER_LOOKUP_BLANK("command.error.player-lookup-blank"),
    COMMAND_ERROR_UNKNOWN_LOCAL_PLAYER("command.error.unknown-local-player"),
    COMMAND_ERROR_ID_BLANK("command.error.id-blank"),
    COMMAND_ERROR_ID_REQUIRED("command.error.id-required"),
    COMMAND_ERROR_ID_INVALID_CHARACTER("command.error.id-invalid-character"),
    COMMAND_ERROR_NAME_BLANK("command.error.name-blank"),
    COMMAND_ERROR_CUSTOM_NAME_EMPTY("command.error.custom-name-empty"),
    COMMAND_ERROR_CATEGORY_ID_BLANK("command.error.category-id-blank"),
    COMMAND_ERROR_CATEGORY_NAME_BLANK("command.error.category-name-blank"),
    COMMAND_ERROR_TEXTURE_EMPTY("command.error.texture-empty"),
    COMMAND_ERROR_TEXTURE_REQUIRED("command.error.texture-required"),
    COMMAND_ERROR_TEXTURE_NOT_HEAD("command.error.texture-not-head"),
    COMMAND_ERROR_TEXTURE_NO_PROFILE("command.error.texture-no-profile"),
    COMMAND_ERROR_TEXTURE_NO_PROPERTY("command.error.texture-no-property"),
    COMMAND_ERROR_TEXTURE_NO_URL("command.error.texture-no-url"),
    COMMAND_ERROR_TEXTURE_NO_HASH("command.error.texture-no-hash"),
    COMMAND_ERROR_TEXTURE_HASH_EMPTY("command.error.texture-hash-empty"),
    COMMAND_ERROR_TEXTURE_HASH_HEX("command.error.texture-hash-hex"),

    COMMAND_GIVE_SUCCESS("command.give.success"),
    COMMAND_GIVE_RECEIVED("command.give.received"),

    COMMAND_RELOAD_STARTED("command.reload.started"),
    COMMAND_RELOAD_SUCCESS("command.reload.success"),
    COMMAND_RELOAD_FAILED("command.reload.failed"),

    COMMAND_REFRESH_ALREADY_RUNNING("command.refresh.already-running"),
    COMMAND_REFRESH_STARTED("command.refresh.started"),

    COMMAND_VERIFY_ALREADY_RUNNING("command.verify.already-running"),
    COMMAND_VERIFY_STARTED("command.verify.started"),
    COMMAND_VERIFY_SUCCESS("command.verify.success"),
    COMMAND_VERIFY_FAILED("command.verify.failed"),

    COMMAND_ITEMCACHE_CLEARED("command.itemcache.cleared"),

    COMMAND_UPDATE_CHECKING("command.update.checking"),

    COMMAND_CUSTOM_LIST_HEADER("command.custom.list-header"),
    COMMAND_CUSTOM_LIST_EMPTY("command.custom.list-empty"),
    COMMAND_CUSTOM_INFO_HEADER("command.custom.info-header"),
    COMMAND_CUSTOM_INFO_ID("command.custom.info.id"),
    COMMAND_CUSTOM_INFO_CATEGORY("command.custom.info.category"),
    COMMAND_CUSTOM_INFO_TAGS("command.custom.info.tags"),
    COMMAND_CUSTOM_INFO_COLLECTIONS("command.custom.info.collections"),
    COMMAND_CUSTOM_INFO_TEXTURE("command.custom.info.texture"),
    COMMAND_CUSTOM_CREATED("command.custom.created"),
    COMMAND_CUSTOM_CREATED_HELD("command.custom.created-held"),
    COMMAND_CUSTOM_DELETED("command.custom.deleted"),
    COMMAND_CUSTOM_DELETE_MISSING("command.custom.delete-missing"),
    COMMAND_CUSTOM_RENAMED("command.custom.renamed"),

    COMMAND_EDIT_REMOTE_ONLY("command.edit.remote-only"),
    COMMAND_EDIT_OVERRIDE_PRESENT("command.edit.override-present"),
    COMMAND_EDIT_OVERRIDE_NONE("command.edit.override-none"),
    COMMAND_EDIT_SAVED("command.edit.saved"),
    COMMAND_EDIT_RESET("command.edit.reset"),
    COMMAND_EDIT_RESET_MISSING("command.edit.reset-missing"),

    COMMAND_PLAYER_RESOLVING("command.player.resolving"),
    COMMAND_PLAYER_RESOLVE_FAILED("command.player.resolve-failed"),

    COMMAND_REPORT_HEADER("command.report.header"),
    COMMAND_REPORT_PASTE_HINT("command.report.paste-hint"),

    // Economy

    ECONOMY_INVALID_FUNDS("economy.invalid-funds"),
    ECONOMY_PURCHASED("economy.purchased"),

    // GUI

    GUI_LANGUAGE_CHANGED("gui.language.changed"),
    GUI_LANGUAGE_RESET("gui.language.reset"),
    GUI_PRICE_INVALID("gui.price.invalid"),
    GUI_PRICE_UPDATED("gui.price.updated"),
    GUI_TAXONOMY_CREATED("gui.taxonomy.created"),
    GUI_TAXONOMY_DELETED("gui.taxonomy.deleted"),
    GUI_TAXONOMY_UNKNOWN("gui.taxonomy.unknown"),
    GUI_TAXONOMY_ID_PROMPT("gui.taxonomy.id-prompt"),
    GUI_TAXONOMY_NAME_PROMPT("gui.taxonomy.name-prompt"),
    GUI_TAXONOMY_DESCRIPTION_PROMPT("gui.taxonomy.description-prompt"),

    GUI_PROMPT_HINT("gui.prompt.hint"),
    GUI_PROMPT_CANCELLED("gui.prompt.cancelled"),

    GUI_SEARCH_PROMPT("gui.search.prompt"),
    GUI_SEARCH_IDS_PROMPT("gui.search.ids-prompt"),
    GUI_SEARCH_CANCELLED("gui.search.cancelled"),
    GUI_SEARCH_INFO_HEADER("gui.search.info.header"),
    GUI_SEARCH_INFO_QUERY("gui.search.info.query"),
    GUI_SEARCH_INFO_SORT("gui.search.info.sort"),

    GUI_TAGS_SEARCH_PROMPT("gui.tags.search-prompt"),
    GUI_COLLECTIONS_SEARCH_PROMPT("gui.collections.search-prompt"),

    GUI_FAVORITE_MISSING("gui.favorites.missing"),
    GUI_FAVORITE_ADDED("gui.favorites.added"),
    GUI_FAVORITE_REMOVED("gui.favorites.removed"),
    GUI_ADMIN_MODE_ENABLED("gui.mode.admin-enabled"),
    GUI_USER_MODE_ENABLED("gui.mode.user-enabled"),
    GUI_ADMIN_MODE_REQUIRED("gui.mode.admin-required"),

    GUI_INVENTORY_FULL("gui.head.inventory-full"),
    GUI_HEAD_MISSING("gui.head.missing"),
    GUI_HEAD_SHOWN("gui.head.shown"),
    GUI_HEAD_VISIBLE("gui.head.visible"),
    GUI_HEAD_HIDDEN("gui.head.hidden"),
    GUI_HIDDEN_ALL_SHOWN("gui.head.all-shown"),
    GUI_HEAD_PRICE_PROMPT("gui.head.price-prompt"),
    GUI_HEAD_PRICE_FAILED("gui.head.price-failed"),
    GUI_HEAD_DRAFT_SAVED("gui.head.draft-saved"),
    GUI_HEAD_DRAFT_PUBLISHED("gui.head.draft-published"),
    GUI_HEAD_ID_PROMPT("gui.head.id-prompt"),
    GUI_HEAD_NAME_PROMPT("gui.head.name-prompt"),
    GUI_HEAD_TEXTURE_PROMPT("gui.head.texture-prompt"),
    GUI_CUSTOM_HEAD_MISSING("gui.head.custom-missing"),
    GUI_CUSTOM_HEAD_MISSING_ID("gui.head.custom-missing-id"),
    GUI_CUSTOM_HEAD_DELETED("gui.head.custom-deleted"),

    GUI_EDIT_UNKNOWN_ACTION("gui.edit.unknown-action"),
    GUI_EDIT_NAME_PROMPT("gui.edit.name-prompt"),
    GUI_EDIT_NAME_UPDATED("gui.edit.name-updated"),
    GUI_EDIT_NAME_CHANGE("gui.edit.name-change"),
    GUI_EDIT_CATEGORY_SET("gui.edit.category-set"),
    GUI_EDIT_OVERRIDE_RESET("gui.edit.override-reset"),
    GUI_EDIT_LORE_ADD_PROMPT("gui.edit.lore-add-prompt"),
    GUI_EDIT_LORE_EDIT_PROMPT("gui.edit.lore-edit-prompt"),
    GUI_EDIT_LORE_ADDED("gui.edit.lore-added"),
    GUI_EDIT_LORE_CLEARED("gui.edit.lore-cleared"),
    GUI_EDIT_LORE_UPDATED("gui.edit.lore-updated"),
    GUI_EDIT_LORE_LINE_REMOVED("gui.edit.lore-line-removed"),
    GUI_EDIT_LORE_RESET("gui.edit.lore-reset"),

    GUI_CATEGORY_HEAD_PROMPT("gui.category.head-prompt"),
    GUI_CATEGORY_HEAD_ADDED("gui.category.head-added"),
    GUI_CATEGORY_HEAD_REMOVED("gui.category.head-removed"),
    GUI_CATEGORY_NAME_PROMPT("gui.category.name-prompt"),
    GUI_CATEGORY_DISPLAY_NAME_PROMPT("gui.category.display-name-prompt"),
    GUI_CATEGORY_DESCRIPTION_PROMPT("gui.category.description-prompt"),
    GUI_CATEGORY_MATERIAL_PROMPT("gui.category.material-prompt"),
    GUI_CATEGORY_HEAD_ICON_PROMPT("gui.category.head-icon-prompt"),
    GUI_CATEGORY_PERMISSION("gui.category.permission"),
    GUI_CATEGORY_ICON_PROMPT("gui.category.icon-prompt"),
    GUI_CATEGORY_PRICE_PROMPT("gui.category.price-prompt"),
    GUI_CATEGORY_PRICE_FAILED("gui.category.price-failed"),
    GUI_CATEGORY_DRAFT_SAVED("gui.category.draft-saved"),
    GUI_CATEGORY_PUBLISHED("gui.category.published"),
    GUI_CATEGORY_SAVED("gui.category.saved"),
    GUI_CATEGORY_DELETED("gui.category.deleted"),
    GUI_CATEGORY_SAVE_FIRST("gui.category.save-first"),
    GUI_CATEGORY_NAME_REQUIRED("gui.category.name-required"),

    GUI_MATERIAL_PROMPT("gui.material.prompt"),
    GUI_MATERIAL_UNKNOWN("gui.material.unknown"),
    GUI_MATERIAL_SET("gui.material.set"),

    GUI_BUTTON_NAME_PROMPT("gui.button.name-prompt"),
    GUI_BUTTON_HEAD_ID_PROMPT("gui.button.head-id-prompt"),
    GUI_BUTTON_LORE_ADD_PROMPT("gui.button.lore-add-prompt"),
    GUI_BUTTON_LORE_EDIT_PROMPT("gui.button.lore-edit-prompt"),
    GUI_BUTTON_TYPE_SET("gui.button.type-set"),
    GUI_BUTTON_RESET("gui.button.reset"),
    GUI_BUTTON_UPDATED("gui.button.updated"),
    GUI_BUTTON_EDIT_CANCELLED("gui.button.edit-cancelled"),
    GUI_BUTTON_LORE_CLEARED("gui.button.lore-cleared"),
    GUI_BUTTON_LORE_RESET("gui.button.lore-reset"),
    GUI_BUTTON_LORE_LINE_REMOVED("gui.button.lore-line-removed"),
    GUI_BUTTON_LORE_UPDATED("gui.button.lore-updated");

    private final String path;

    MessageKey(@NotNull String path) {
        this.path = path;
    }

    public @NotNull String path() {
        return path;
    }
}