headdb.build.channel=${headdb.build.channel}
headdb.build.number=${headdb.build.number}
headdb.build.attempt=${headdb.build.attempt}
headdb.build.run-id=${headdb.build.run-id}
headdb.build.commit=${headdb.build.commit}
headdb.build.branch=${headdb.build.branch}
headdb.build.timestamp=${headdb.build.timestamp}
